# Base directory for all application data (logs + DB)
data.dir=C:\\Users\\SEEMA SINGH\\MyFreeLance\\LabReport2\\labreport\\data\\
report.path=C:\\Users\\SEEMA SINGH\\MyFreeLance\\LabReport2\\labreport\\report-assets\\